export type DirectoryTier = 1 | 2 | 3 | 4;

export type DirectoryTarget = {
  id: string;
  platform: string;
  signupUrl: string;
  tier: DirectoryTier;
  estimatedMinutes: number;
  loginRequired: boolean;
  suggestedCategories: string[];
  notes?: string;
};

/** Tier 1 = highest local impact; Tier 4 = trade vertical. */
export const DIRECTORY_TARGETS: DirectoryTarget[] = [
  {
    id: "gbp",
    platform: "Google Business Profile",
    signupUrl: "https://business.google.com",
    tier: 1,
    estimatedMinutes: 20,
    loginRequired: true,
    suggestedCategories: ["Excavating contractor", "Construction company"],
    notes: "Verify ownership; set website to .ca; add service areas and photos.",
  },
  {
    id: "bing-places",
    platform: "Bing Places",
    signupUrl: "https://www.bingplaces.com",
    tier: 1,
    estimatedMinutes: 15,
    loginRequired: true,
    suggestedCategories: ["Excavating contractor"],
  },
  {
    id: "apple-business",
    platform: "Apple Business Connect",
    signupUrl: "https://businessconnect.apple.com",
    tier: 1,
    estimatedMinutes: 15,
    loginRequired: true,
    suggestedCategories: ["Construction"],
  },
  {
    id: "yellow-pages-ca",
    platform: "Yellow Pages Canada",
    signupUrl: "https://www.yellowpages.ca",
    tier: 1,
    estimatedMinutes: 10,
    loginRequired: true,
    suggestedCategories: ["Excavation Contractors"],
  },
  {
    id: "canada411",
    platform: "Canada411",
    signupUrl: "https://www.canada411.ca",
    tier: 1,
    estimatedMinutes: 10,
    loginRequired: true,
    suggestedCategories: ["Excavating contractor"],
  },
  {
    id: "homestars",
    platform: "HomeStars",
    signupUrl: "https://www.homestars.com",
    tier: 1,
    estimatedMinutes: 15,
    loginRequired: true,
    suggestedCategories: ["Excavation"],
    notes: "Upload project photos; request reviews after jobs.",
  },
  {
    id: "houzz",
    platform: "Houzz Pro",
    signupUrl: "https://www.houzz.com/pro",
    tier: 1,
    estimatedMinutes: 15,
    loginRequired: true,
    suggestedCategories: ["Excavation"],
  },
  {
    id: "barrie-chamber",
    platform: "Barrie Chamber of Commerce",
    signupUrl: "https://www.barriechamber.com",
    tier: 2,
    estimatedMinutes: 20,
    loginRequired: true,
    suggestedCategories: ["Construction / Excavation"],
    notes: "Membership may be required for directory link.",
  },
  {
    id: "orillia-chamber",
    platform: "Orillia & District Chamber of Commerce",
    signupUrl: "https://www.orillia.com/chamber",
    tier: 2,
    estimatedMinutes: 20,
    loginRequired: true,
    suggestedCategories: ["Construction"],
    notes: "Membership may be required for directory link.",
  },
  {
    id: "bbb-central-ontario",
    platform: "BBB Central Ontario",
    signupUrl: "https://www.bbb.org",
    tier: 2,
    estimatedMinutes: 15,
    loginRequired: true,
    suggestedCategories: ["Excavating contractor"],
  },
  {
    id: "trustedpros",
    platform: "TrustedPros",
    signupUrl: "https://www.trustedpros.ca",
    tier: 2,
    estimatedMinutes: 10,
    loginRequired: true,
    suggestedCategories: ["Excavation"],
  },
  {
    id: "facebook",
    platform: "Facebook Business Page",
    signupUrl: "https://www.facebook.com/pages/create",
    tier: 3,
    estimatedMinutes: 10,
    loginRequired: true,
    suggestedCategories: ["Construction Company"],
  },
  {
    id: "linkedin",
    platform: "LinkedIn Company Page",
    signupUrl: "https://www.linkedin.com/company/setup/new",
    tier: 3,
    estimatedMinutes: 10,
    loginRequired: true,
    suggestedCategories: ["Construction"],
  },
  {
    id: "yelp-ca",
    platform: "Yelp Canada",
    signupUrl: "https://biz.yelp.ca",
    tier: 3,
    estimatedMinutes: 10,
    loginRequired: true,
    suggestedCategories: ["Excavation Services"],
  },
  {
    id: "brownbook",
    platform: "Brownbook.net",
    signupUrl: "https://www.brownbook.net",
    tier: 3,
    estimatedMinutes: 8,
    loginRequired: true,
    suggestedCategories: ["Excavating contractor"],
  },
  {
    id: "cylex-ca",
    platform: "Cylex Canada",
    signupUrl: "https://www.cylex-canada.ca",
    tier: 3,
    estimatedMinutes: 8,
    loginRequired: true,
    suggestedCategories: ["Excavating contractor"],
  },
  {
    id: "hotfrog-ca",
    platform: "Hotfrog Canada",
    signupUrl: "https://www.hotfrog.ca",
    tier: 3,
    estimatedMinutes: 8,
    loginRequired: true,
    suggestedCategories: ["Excavation"],
  },
  {
    id: "iglobal",
    platform: "iGlobal",
    signupUrl: "https://www.iglobal.co/canada",
    tier: 3,
    estimatedMinutes: 8,
    loginRequired: true,
    suggestedCategories: ["Construction"],
  },
  {
    id: "cybo",
    platform: "Cybo",
    signupUrl: "https://www.cybo.com",
    tier: 3,
    estimatedMinutes: 8,
    loginRequired: true,
    suggestedCategories: ["Excavating contractor"],
  },
  {
    id: "manta",
    platform: "Manta",
    signupUrl: "https://www.manta.com/add-your-business",
    tier: 3,
    estimatedMinutes: 8,
    loginRequired: true,
    suggestedCategories: ["Excavation contractor"],
  },
  {
    id: "ogca",
    platform: "Ontario General Contractors Association",
    signupUrl: "https://ogca.ca",
    tier: 4,
    estimatedMinutes: 25,
    loginRequired: true,
    suggestedCategories: ["Subcontractor / Supplier"],
    notes: "Explore membership or supplier directory eligibility.",
  },
];

export function getDirectoriesByTier(tier: DirectoryTier): DirectoryTarget[] {
  return DIRECTORY_TARGETS.filter((d) => d.tier === tier);
}
